#!/bin/sh
## gcc for  in /home/penava_b/perso/Obj/Obj4/Future/compiler
## 
## Made by penava_b
## Login   <penava_b@epitech.net>
## 
## Started on  Wed May 11 02:18:25 2016 penava_b
## Last update Tue May 24 00:13:34 2016 penava_b
##

gcc -no-integrated-cpp -wrapper ./compile-caller -std=c99 $@ \
    -fplan9-extensions -finstrument-functions -Wfatal-errors;
