#!/bin/bash
# Copyright (C) 2016  Bastien Penavayre

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

function precompiler()
{
    if [ -z $arg ]; then
        $@ -CC -D__OBJECT_C_COMPILER__ | cpp;
        exit $?;
    fi;
    $@ -CC -D__OBJECT_C_COMPILER__;
    ret=$?
    if [ $ret == 0 ];
    then
        cpp $arg -o $arg.precompiled.c;
        mv $arg.precompiled.c $arg;
    fi;
    exit $ret;
}

function compiler_call()
{
    local ret arg
    if [ `basename $1` = "cc1" ] && [ "$2" = "-E" ] || [ `basename $1` = "cpp" ];
    then
        for i in `seq 1 $#`;
        do
            case ${!i} in
                -o*)
                    i=$(echo $i+1 | bc)
                    break;
                    ;;
                -o)
                    break;
                    ;;
            esac;
        done;
        arg=`echo ${!i} | awk -F '-o' '{print $NF}'`
        precompiler $@
    else
        $@;
        exit $?;
    fi;
}

if [ $OBJECT_C_DEBUG ]; then
    echo "$@";
fi;
compiler_call $@;
